### ISSUE TITLE
Managing gaps in data

### ISSUE THREAD

**Issue by Lucile-Costes** [seisman/HinetPy#103]
I am a phd student, working with data from HiNet and FNet. I am currently retrieving the data, converting them with win2sac... And it seems to me that win32tools automatically fills gaps with zeros. I don't know if it is the right place to ask this kind of question but I am therefore wondering (first if I am right) how do you manage gaps in data ? 
Thanks in advance for your answer,
Lucile Costes

**Comment by seisman** [comment]
I'm not sure how `win2sac` deal with gaps, but HinetPy calls `win2sac` to merge data, so it `win2sac` fills gaps with zeros, then HinetPy does exactly the same thing.

Filling gaps with zeros may appropriate or not, depending on how you will use the data.

**Comment by Lucile-Costes** [comment]
Ok, thank you for your answer, it confirms what I was planning to do.
