### ISSUE TITLE
Reference for the unit of data in sac files

### ISSUE THREAD

**Issue by zhong-yy** [seisman/HinetPy#108]
**Description of the solution you'd like**

May I ask how you know the instrumental response has been removed in sac files and the converted sac files are velocity/acceleration? Do you mind giving any references in the documentation (https://seisman.github.io/HinetPy/tutorial/conversion.html)?

I failed to find descriptions about the output data format on the win32tools documentation (https://hinetwww11.bosai.go.jp/auth/manual/?LANG=en)

**Comment by seisman** [comment]
You have to read the win32tools source code to understand the data output:

Near line 145 in `s4win2sac0.c`, you'll see that after reading the win32 data, the source code multiple the data by *sense* and 1.0e9.
```
    for (i = 0; i < npts; i++) {                                                        
        if (giKunit == 1 || giKunit == 2) { /** m/s or m/s/s **/                        
            yfunc[i] = yfunc[i] * sense * 1000000000.0; /** nm/s or nm/s/s **/          
        } else if (giKunit == 3) { /** rad **/                                          
            yfunc[i] = yfunc[i] * sense * 1000000.0;  /** micro rad **/                 
        } else {                                                                        
            yfunc[i] = yfunc[i] * sense;                                                
        }                                                                               
    }
```
and *sense* is calculated in `s4stfind.c` (line 130):
```
sense = (adc / (float) pow(10.0, (double) gain / 20.0)) / (float) vu;
```

In HinetPy, the equivalent code is:
https://github.com/seisman/HinetPy/blob/d5274f9c913e3824e1caa3f0336494033974f932/HinetPy/win32.py#L118-L119

**Comment by zhong-yy** [comment]
Thank you very much for the detailed explanation!
