### ISSUE TITLE
SSLError(1, '[SSL: DH_KEY_TOO_SMALL]

### ISSUE THREAD

**Issue by stefanazzz** [seisman/HinetPy#113]
Using HinetPy==0.8.0            
Python 3.10.6
Linux

the following code works but crashes whenever including 
select_stations or get_station_list, error SSL: DH_KEY_TOO_SMALL

-------------------------------
CODE EXAMPLE:
--------------------------------
# This part works ok, 
# however returns only 6 traces (2 stations N.IWEH  N.IWSH)
from HinetPy import Client, win32
client = Client("username", "password")
client.doctor()
client.info("0101")
client.get_event_waveform(
    "201001010000",
    "201001020000",
    minmagnitude=4.0,
    maxmagnitude=7.0,
    mindepth=0,
    maxdepth=70)
data, ctable = client.get_continuous_waveform("0101", "2020301010000", 2)
win32.extract_sac(data, ctable, suffix="", outdir="SAC")

# The following commands crash with error
# SLError(1, '[SSL: DH_KEY_TOO_SMALL] dh key too small (_ssl.c:997)'):

stations = client.get_station_list("0101") # crash
client.select_stations("0101", ["N.AAKH", "N.ABNH"]) #crash
client.select_stations("0101", latitude=36, longitude=139, minradius=0, maxradius=3) # crash
-------------------------------------------------------------  
possibly related issue 

skip SSL verification by using `verify=False`.

_Originally posted by @seisman in https://github.com/seisman/HinetPy/issues/1#issuecomment-65390038_

HOW / WHERE DO I SET verify = FALSE ? i tried this but no luck:

client = Client("stefanazzz", "S2ByXcxUurfz", verify=False)
--> TypeError: BaseClient.__init__() got an unexpected keyword argument 'verify'

stations = client.get_station_list("0101", verify = False)
--> TypeError: StationClient.get_station_list() got an unexpected keyword argument 'verify'

Many thanks,
Stefanazzz

**Comment by stefanazzz** [comment]
btw, I can't install higher than urlib3==urllib3-1.26.18 for some compatibility strangely

**Comment by seisman** [comment]
It's very likely something wrong with Python 3.10. Is upgrading your Python to 3.11 an option for you?

**Comment by seisman** [comment]
Or you may try HinetPy v0.7.1 instead.

**Comment by stefanazzz** [comment]
Thanks seisman, I did try also HinetPy==0.7.1, unfortunately same error
(I have I changed my password after the above post... :)

**Comment by seisman** [comment]
From https://stackoverflow.com/questions/38015537/python-requests-exceptions-sslerror-dh-key-too-small, the reasons seem very complicated. I don't have enough knowledge to fix the issue, but the CI tell me that the package should work well on newer Python versions. I guess upgrading your Python to 3.11 or 3.12 is the easiest solution.

**Comment by stefanazzz** [comment]
thanks Dongdong, I will try the python upgrade. 
S

**Comment by stefanazzz** [comment]
Yes! installing HynetPy under python 3.12 fixed the issue!
thanks
St

**Comment by seisman** [comment]
Good to know that it works for you. Closing.
