### ISSUE TITLE
Error: While the data is being created, you cannot be new request.

### ISSUE THREAD

**Issue by peanut-butterabc** [seisman/HinetPy#123]
Hi @seisman 

**Description of the problem**
We found that sometimes data cannot be downloaded using `get_continuous_waveform`. Then we looked at the error message on the website of Hinet, we saw the error reported as 'While the data is being created, you cannot be new request.' .

<img width="985" alt="Screenshot 2024-07-10 at 7 19 36 PM" src="https://github.com/seisman/HinetPy/assets/175214215/02ead783-aac6-4945-b150-e06cfd99d7b8">

We doubt that it is due to the `threads` argument because when we set  `thread = 1`,  the data can be downloaded successfully.

May I ask for the possible cause(s) of this error? If it is caused by `thread`, is there any other solution apart from specifying `thread=1`?

------------------------------------------------------------------------------------
**Full code that generated the error**

```python
client = ... 
time_window=90
t_start=UTCDateTime("2024-01-15T20:30:00.000000")
data, ctable = client.get_continuous_waveform(
    "030243", # 030243 : JMA Volcanic Seismometer Network (Sakurajima)
    starttime=datetime.fromisoformat(t_start.isoformat()),
    span=time_window,
    outdir="tmp_dir",
)
```
------------------------------------------------------------------------------------
**System information**

- OS: macOS
- Python version: `python 3.9`
- HinetPy version: `0.9.0`
- Software used: VS Code

**Comment by seisman** [comment]
> We doubt that it is due to the `threads` argument because when we set `thread = 1`, the data can be downloaded successfully.

The `threads` argument only controls the *download* process, and has nothing to do with the *request* process. So `threads` won't cause the issue here.

> May I ask for the possible cause(s) of this error?

Maybe you're running the data request scripts simultaneously in two different terminals? 

Or the data you're requesting is too big which takes much longer time. In this case, you can try to increase the `retries`/`sleep_time_in_seconds`/`max_sleep_count` arguments when initalize the `Client` object. Let me know if it works for you.

**Comment by peanut-butterabc** [comment]
@seisman Thanks for your analysis!

No, I didn't run the data request scripts simultaneously in more than 1 terminals.

Ok! I'll try increasing `retries` / `sleep_time_in_seconds` / `max_sleep_count` arguments when initialise the `Client` object, and will reply after concluding if this works.

**Comment by peanut-butterabc** [comment]
Hi @seisman 

Yes, the command of data requesting works after enlarging the values in these 3 arguments.

Thank you for your help and attention!

**Comment by seisman** [comment]
It's good to know that it works. I am closing the issue.

Just want to remind that, HinetPy now has a formal citation. If you want to cite HinetPy, please cite this short paper published on JOSS. Thanks.

> Tian, D. (2024). HinetPy: A Python package for accessing and processing NIED Hi-net seismic data. Journal of Open Source Software, 9(98), 6840. https://doi.org/10.21105/joss.06840
