### ISSUE TITLE
Downloading F-net (and other) data from before 2004

### ISSUE THREAD

**Issue by JameAtkins** [seisman/HinetPy#124]
**Description of the desired feature**

I'd like to download F-net data earlier than 2004, but I'm being met with an error saying "ValueError: Data not available in the time period. Call Client.info('0103') for help.". When I called Client.info('0103'), it gives a hardcoded start date of April 1, 2004. However, on the [F-net website](https://www.fnet.bosai.go.jp/st_info/?LANG=en) it lists the F-net network ramping up between 1995 and 2004, with a majority being in place before the end of 2000. I saw that [FnetPy](https://github.com/seisman/FnetPy/blob/master/FnetPy/client.py) was able to download data from 1995 onwards and was wondering if this could be ported to HinetPy as well?

Also, I was wondering what unit of measurement the output SAC files from win32.extract_sac is for F-net stations? In the [documentation](https://seisman.github.io/HinetPy/api/HinetPy.win32.html#HinetPy.win32.extract_sac) it says it could either be velocity or acceleration, but it would be useful to note (in the output SAC stats maybe) which of these it is on a station-by-station basis.

**Comment by seisman** [comment]
> I'd like to download F-net data earlier than 2004, but I'm being met with an error saying "ValueError: Data not available in the time period. Call Client.info('0103') for help.". When I called Client.info('0103'), it gives a hardcoded start date of April 1, 2004. 

The Hi-net website only provides data since 2004, so it's impossible to request data before 2004 using HinetPy.

> However, on the [F-net website](https://www.fnet.bosai.go.jp/st_info/?LANG=en) it lists the F-net network ramping up between 1995 and 2004, with a majority being in place before the end of 2000. I saw that [FnetPy](https://github.com/seisman/FnetPy/blob/master/FnetPy/client.py) was able to download data from 1995 onwards and was wondering if this could be ported to HinetPy as well?

I would suggest you use FnetPy for Fnet. Hopefully FnetPy still works.





> Also, I was wondering what unit of measurement the output SAC files from win32.extract_sac is for F-net stations? In the [documentation](https://seisman.github.io/HinetPy/api/HinetPy.win32.html#HinetPy.win32.extract_sac) it says it could either be velocity or acceleration, but it would be useful to note (in the output SAC stats maybe) which of these it is on a station-by-station basis.

Fnet has both broadband and strong-motion stations. In HinetPy, their codes are 0103 and 0103A, respectively. The output SAC files are velocity/acceleration for broadband/strong-motion stations, respectively.

**Comment by JameAtkins** [comment]
Thanks for the quick reply! I wasn't aware of the limitation of Hi-net only providing data after 2004, I'll try FnetPy in those cases.

**Comment by seisman** [comment]
I am closing the issue.

Just want to remind that, HinetPy now has a formal citation. If you want to cite HinetPy, please cite this short paper published on JOSS. Thanks.

> Tian, D. (2024). HinetPy: A Python package for accessing and processing NIED Hi-net seismic data. Journal of Open Source Software, 9(98), 6840. https://doi.org/10.21105/joss.06840
