### ISSUE TITLE
Download fail client.py

### ISSUE THREAD

**Issue by rokuwaki** [seisman/HinetPy#21]
Hi! 

I tried to download continuous waveform data, but I got "ERROR: Data request fails after 3 retries.", and I got no data (*.cnt) and channel table (*.ch) in the working directory. Below is what I got:

```
>>> from HinetPy import Client, win32
>>> client = Client('MYUSENAME', 'MYPASSWORD')
>>> data, ctable = client.get_continuous_waveform('0101', '201604160100', 5)
[2019-07-31 11:12:29] INFO: 2016-04-16 01:00 ~5
[2019-07-31 11:12:29] INFO: [1/1] => 2016-04-16 01:00 ~5
[2019-07-31 11:13:03] ERROR: Data request fails after 3 retries.
[2019-07-31 11:13:03] ERROR: Fail to request some data. Skipped.
```

It seems that the request has successfully been sent to Hi-net, and I could manually (click and save) download the data via Status / Download page at Hi-net website https://hinetwww11.bosai.go.jp/auth/download/cont/cont_status.php?LANG=en, but it should be not convenient for me when downloading hours and days of long data... 

It would be a great help if I could get any hints to solve this problem... Thanks!

 - OS: macOS
 - Python version: Python 3.6.1 
 - HinetPy version: 0.6.3

![HinetPy_error_report_190731113842](https://user-images.githubusercontent.com/8126218/62179539-e4144000-b387-11e9-9245-c035aeee2f33.png)

**Comment by seisman** [comment]
@rokuwaki Your Python script works for me. So it's a little difficult to help you.

Did you run multiple data requesting scripts at the same time? Your script tries to request data of 20160416, but your screenshot shows some other data requests for 20190101. Hinet doesn't allow request multiple data at the same time.

**Comment by rokuwaki** [comment]
@seisman Thanks for your prompt answer, and appreciate that you checked the problem! I know that you do not recommend to do this, but I successfully downloaded the data by modifying `sleep_time_in_seconds` to 10 sec in Client. Here is what I did:

```python
>>> from HinetPy import Client, win32
>>> client = Client('MYUSERNAME', 'MYPASSWORD', sleep_time_in_seconds=10)
>>> data, ctable = client.get_continuous_waveform('0101', '201604160100', 5)
[2019-07-31 13:04:22] INFO: 2016-04-16 01:00 ~5
[2019-07-31 13:04:22] INFO: [1/1] => 2016-04-16 01:00 ~5
```

```bash
$ ls
0101_20160416.ch  0101_201604160100_5.cnt
```

Thank you so much for your beautiful codes, anyways! I could not get over the "unfriendness and limitations of Hi-net website" without your hard work ;) Huge thanks from Japan!

**Comment by seisman** [comment]
Glad to know that it works. `sleep_time_in_seconds=10` is a reasonable value. 

Close this issue. Feel free to reopen the issue or open another issue if you have any further questions.
