### ISSUE TITLE
Hi-net continuous waveform data header and PZ Response files

### ISSUE THREAD

**Issue by Faisal-Umer** [seisman/HinetPy#80]
I have downloaded continuous waveform data of two Hi-net stations using HinetPy. But the problem is when I open the header of any sac file in SAC, there is no network name in it and this in turn is creating problem in station pair making in MSNoise. Furthermore, as I am a newbie in this field, I am also struggling with the response files of the stations. I have PZ response files but I want the response files to be in Station XML. I am unable to understand how to convert these PZ files to Station XML. I am hoping to get some help from here.

**Comment by seisman** [comment]
> But the problem is when I open the header of any sac file in SAC, there is no network name in it and this in turn is creating problem in station pair making in MSNoise.

HinetPy calls the `win2sac_32` command in the win32tools packages to do the data format conversion. The SAC files produced by `win2sac_32` don't have network information. I think you need to read SAC files and add the network information yourself.

> I have PZ response files but I want the response files to be in Station XML. I am unable to understand how to convert these PZ files to Station XML.

I don't know any tool that can convert PZ files to Station XML. You can simply use these PZ files to remove instrumental responses.

**Comment by Faisal-Umer** [comment]
Hi-net has 3 sample resp files on Response of Observation Equipment page. From the channel table file, I have found that Hi-net station 3 is the instrument response file I am looking for. Now in the response of observation equipment, it is mentioned that the 37th line from the top and 4th line from the bottom should be modified. Although, the PZ file that I got when converted the win32 file to sac file has different poles and zeros, and the 8th column of channel table shows 170 value, I am confused what values should I put in 37th line (Gain) from the top and 4th line (Sensitivity) from the bottom. And are these the only modifications that I need to make beside changing the poles and zeros?

**Comment by seisman** [comment]
Why don't you just remove instrumental responses using the SAC PZ files? I believe it's a much easier way.

**Comment by Faisal-Umer** [comment]
Actually I am working in MSNoise where PZ file does not work. Therefore, it is required to convert the response file to Station XML. But before that, I need to make a RESP file according to the channel file.
