### ISSUE TITLE
Downloading waveforms for a single event

### ISSUE THREAD

**Issue by zhong-yy** [seisman/HinetPy#96]
**Description of the desired feature**
Downloading waveforms for a single event, given the event information

**Description of the solution you'd like**
`get_event_waveform` is used to download waveforms for a list of events. Is there any way to download waveforms for only one single event? Now I have downloaded a catalog of events, and I am trying to download waveforms corresponding to each event.

It seems that `_request_event_waveform` and `_download_event_waveform` can do this, but I don't know how to initialize an event. In particular, I am very confused about the event id, because I cannot find any event ID information from the event catalog (https://www.data.jma.go.jp/svd/eqev/data/bulletin/data/format/hypfmt_e.html) 

Thank you for sharing such a convenient package.

**Comment by seisman** [comment]
Let me first explain how you can download event waveforms from the Hinet website:

1. Visit this page https://hinetwww11.bosai.go.jp/auth/download/event/?LANG=en
2. Select the event search parameter and click the "Event Search" button. Then you will see a table of available events:
<img width="833" alt="image" src="https://github.com/seisman/HinetPy/assets/3974108/c0eac002-62bb-4ebd-9c71-48346f94a279">
3. For the events you're interested, click the "Download" button. Then you'll be redirected to the event status page (https://hinetwww11.bosai.go.jp/auth/download/event/event_status.php?LANG=en&page=1) and you can see the ID in the first column:
<img width="1094" alt="image" src="https://github.com/seisman/HinetPy/assets/3974108/4996772c-5129-49f2-a21b-9d7563cce02e">
4. Click the "Dos/Windows" or "Unix" button to download the waveform

So, the `get_event_waveform` does exactly the same thing and the ID shown on the Status page is the one used in `_download_event_waveform`. As you can see, the ID is unique for each request and it has nothing to do with any events.

> Now I have downloaded a catalog of events, and I am trying to download waveforms corresponding to each event.

I think you have two options:

1. Use the `get_continuous_waveform` function (see https://seisman.github.io/HinetPy/examples/example2.html for an example)
2. Use the `get_event_waveform` function but use very strict search parameters to make sure only a single event is returned.

**Comment by zhong-yy** [comment]
Thanks for the clear explanation. I am trying using `get_event_waveform` with very strict search parameters. It seems that the hypocenter information from the [JMA unified catalog](https://hinetwww11.bosai.go.jp/auth/JMA/?LANG=en) is slightly different from that on the [Event Waveform Data Download](https://hinetwww11.bosai.go.jp/auth/download/event/) page. If the search parameters for `get_event_waveform` are too strict, then no data can satisfy the conditions.

For example, for this event, the origin time is `2004-04-06T00:23:25.840000Z`, the latitude is `35+3.75/60=35.0625`, the longitude is `137.4888`
![image](https://github.com/seisman/HinetPy/assets/38816011/ac74110c-2df6-41eb-ace8-08465c999e51)

The event from [Event Waveform Data Download](https://hinetwww11.bosai.go.jp/auth/download/event/) is
![image](https://github.com/seisman/HinetPy/assets/38816011/4474fb84-7f31-4bc0-9ef2-e09ab23b93b9)

**Comment by seisman** [comment]
> 1. Use the `get_continuous_waveform` function (see https://seisman.github.io/HinetPy/examples/example2.html for an example)

Maybe this one is better.

**Comment by zhong-yy** [comment]
Thank you. Using `get_continuous_waveform` is much slower, because too many waveforms are downloaded. I will  `get_event_waveform`  with a small (but not too small) search region. 

Maybe it would be better if `get_event_waveform` can return a list of directory names for successful downloads.
