### ISSUE TITLE
Error in parsing channel information for NU.NIN

### ISSUE THREAD

**Issue by zhong-yy** [seisman/HinetPy#98]
**Full error message**
```
[2023-07-21 10:20:42] WARNING: Error in parsing channel information for NU.NIN.U (9181). Skipped.
[2023-07-21 10:20:42] WARNING: Original error message: could not convert string to float: '0.70-10'
[2023-07-21 10:20:42] WARNING: Error in parsing channel information for NU.NIN.N (9182). Skipped.
[2023-07-21 10:20:42] WARNING: Original error message: could not convert string to float: '0.70-10'
[2023-07-21 10:20:42] WARNING: Error in parsing channel information for NU.NIN.E (9183). Skipped.
[2023-07-21 10:20:42] WARNING: Original error message: could not convert string to float: '0.70-10'
```

I guess this message stems from the following code
https://github.com/seisman/HinetPy/blob/4481ba955a71c65f233bcd2bd86387ab5d5f439a/HinetPy/win32.py#L380-L387

The erroneous station is 
```
# nu.nin Niino
9181  1  0  NU.NIN  U     7   20  1500.00  m/s    120.05  0.70-10  7.630e-06  34.6833 138.1312    55  0  0  Niino
9182  1  0  NU.NIN  N     7   20  1500.00  m/s    120.05  0.70-10  7.630e-06  34.6833 138.1312    55  0  0  Niino
9183  1  0  NU.NIN  E     7   20  1500.00  m/s    120.05  0.70-10  7.630e-06  34.6833 138.1312    55  0  0  Niino
```
which is from this channel table [D20110514001274_20.txt](https://github.com/seisman/HinetPy/files/12115767/D20110514001274_20.txt)

**System information**

- OS: Ubuntu 22.04
- Python version: Python 3.9.16
- HinetPy version: v0.7.2.dev15+g992f9b8

**Comment by seisman** [comment]
There must be something wrong with these channels. `0.70-10` is not a valid float value.

**Comment by zhong-yy** [comment]
I don't know the format of the channel table. I guess `0.70-10` may be two numbers, because a normal record looks like
```
# nu.hed Heda
91b1  0  0  NU.HED  U     3   20   230.00  m/s     1.00  0.70 12  7.630e-06  34.9625 138.8097   160  0  0  Heda
91b2  0  0  NU.HED  N     3   20   230.00  m/s     1.00  0.70 12  7.630e-06  34.9625 138.8097   160  0  0  Heda
91b3  0  0  NU.HED  E     3   20   230.00  m/s     1.00  0.70 12  7.630e-06  34.9625 138.8097   160  0  0  Heda
```

**Comment by seisman** [comment]
That's a good point. What's the network code for these channels? Or could you please share the script you used to download the data so that I can try to reproduce it.

**Comment by seisman** [comment]
That's a good point. What's the network code for these channels? Or could you please share the script you used to download the data so that I can try to reproduce it.

**Comment by zhong-yy** [comment]
Here is a minimum example
```python
org_time=UTCDateTime("2012-12-17T21:32:52.140000Z")
client.get_event_waveform(
    datetime.fromisoformat((org_time - 0.1).isoformat()),
    datetime.fromisoformat((org_time + 0.1).isoformat()),
    minmagnitude=0.6 - 0.1,
    maxmagnitude=0.6 + 0.1,
    mindepth=43.25 - 1,
    maxdepth=43.25 + 1,
    minlatitude=40.5675 - 0.01,
    maxlatitude=40.5675 + 0.01,
    minlongitude=141.153 - 0.01,
    maxlongitude=141.153 + 0.01,
)
data = f"D20121217000574_20/D20121217000574_20.evt"
ctable = f"D20121217000574_20/D20121217000574_20.ch"
HinetPy.win32.extract_sac(
    data,
    ctable,
    filter_by_name=list(event_waveforms["station_code"]),
    outdir=dirnames[0],
)
```

**Comment by seisman** [comment]
I'm not sure what I can do here.

Currently, channel information in the channel table file is extracted by the following code:

https://github.com/seisman/HinetPy/blob/4481ba955a71c65f233bcd2bd86387ab5d5f439a/HinetPy/win32.py#L363

The code assumes fields are separated by whitespaces. It works well for most channels except `NU.NIN`, which has an invalid field `0.70-10`.
